export const GAME_CONFIG = {
  startingCredits: 1_000,
  defaultBet: 10,
  minimumBet: 1,
  maximumBet: 100,
  betIncrement: 1,
  rows: 3,
  columns: 5,
  beerFreeSpins: 10,
  cigaretteFreeSpins: 3,
  cigaretteMultiplierMinimum: 2,
  cigaretteMultiplierMaximum: 10,
  belowThresholdTriggerChances: {
    BEER: { 1: 0.002, 2: 0.008 },
    CIGARETTE: { 1: 0.005, 2: 0.01 },
  },
  recentEventLimit: 30,
  normalSpinDurationMs: 720,
  quickSpinDurationMs: 180,
  normalEvaluationDelayMs: 420,
  quickEvaluationDelayMs: 90,
} as const;
